### ISSUE TITLE
unable to import didcomm npm

### ISSUE THREAD

**Issue by jaredatron** [sicpa-dlab/didcomm-rust#115]
## What

I was just installing the didcomm npm package and ran into some errors

## Why

I could not find any documentation on the nodejs api so I wanted to install it to discover the api. 

## Success Criteria

install didcomm node package via `pnpm` and import it successfully.

## Anything else

When importing like this:

```js
import * as didcomm from 'didcomm'
```

I got this error:

```
(node:64180) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
/Users/username/Work/jlinc/didcomm-npm-install/node_modules/.pnpm/didcomm@0.4.0/node_modules/didcomm/index.js:1
import * as wasm from "./index_bg.wasm";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1166:20)
    at Module._compile (node:internal/modules/cjs/loader:1210:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1300:10)
    at Module.load (node:internal/modules/cjs/loader:1103:32)
    at Module._load (node:internal/modules/cjs/loader:942:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:168:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
```

I added these two lines to `node_modules/didcomm/package.json`

```json
{
  "type": "module",
  "main": "index.js"
}
```

and it fixed the import problem. 

## My Environment

```
Node v19.5.0
pnpm 7.29.0
Macbook Pro Ventura 13.2.1
```

**Comment by curtis-h** [comment]
Hi, did you try using the `didcomm-node` package? the docs indicate to use that in node envs (without bundler):

![image](https://user-images.githubusercontent.com/5673638/224069732-02edfeb0-69b8-4398-921d-0b8b10771212.png)

hopefully this helps :)

**Comment by jaredatron** [comment]
That did work. I'm a bit embarrassed I didn't try that first. Thank you @curtis-h
